### ISSUE TITLE
Update look and feel blog

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/hermezio-homepage#74]

**Comment by mmilenkovic** [comment]
![Blog Layout fix (1).png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/ce8b7da3-befa-4359-921a-3273933191cd)
[https://app.zenhub.com/files/280208599/6744ba73-4f6f-4845-9e9a-db06fa81af48/download](https://app.zenhub.com/files/280208599/6744ba73-4f6f-4845-9e9a-db06fa81af48/download)
